### ISSUE TITLE
Fatal crash with Avali and FU

### ISSUE THREAD

**Issue by Xilosc** [xn-5o8h/sbmod_scriptedsail#4]
Frackin Universe has included this mod so it can be used with their custom SAIL. Avali includes FU for whatever reason. And you include Avali. This creates an endless loop of these 3 mods including eachother that causes the game to crash immediately upon opening.

This would be true of any mod that includes FU

**Comment by xn-5o8h** [comment]
Pfhaha really, I had assumed Starbound would be smart enough to not do circular requirements, but I guess I should've tested it out. Will remove Avali from the includes, it doesn't need to be here if FU includes it anyway, since the includes's only here because FU including this mod makes Starbound ignore this mod's priority.

Thanks!

**Comment by Xilosc** [comment]
Thanks for the quick reply! It seems like there's going to be issues getting scripted sail to work with both Avali and FU. Avali actually includes FU to keep some of the items in FU from overwriting their assets. I left them an issue as well on their git. FU included this mod to allow for FU's new sail interface which has a button to access your mod if it's installed. Removing Avali from your includes would fix the crash (and get the FU official game server up and running again) but would mean Avali might not be supported by your SAIL unless you can find a workaround with them

**Comment by Xilosc** [comment]
Might be able to work something out between FU and Avali to fix their includes on our end. If you remove the Avali includes for now until we can get that worked the crashes would be fixed and I'll definitely update you if we can get things cooperating again

**Comment by xn-5o8h** [comment]
> but would mean Avali might not be supported by your SAIL unless you can find a workaround with them

Not sure if that's correct; if people playing with FU as Avalis get their techstation replaced by FU's BYOS magic, then there's no need for the patches to be applied to the avali techstation, since it's not used at all.
And if they don't play with FU, then Scripted S.A.I.L.'s priority of 100 is taken into account, and Starbound would load this mod after after Avali even without it in the includes, so I think it all works out?

**Comment by xn-5o8h** [comment]
This made me check if the other included mods weren't in a similar case, and there was 5.
If they aren't using FU's byos techstation somehow, a workaround would be to simply spawn a different, patched techstation; I mentioned this in this mod's description.

Again, thanks for reporting the issue!
